# docker-compose.yml

version: '3.2'

services:
 db:
   restart: always
   image: postgres
   container_name: APP_NAME_db
   volumes:
     - type: volume
       source: dbdata
       target: /pg_data
   ports:
     - "8001:5432"
 web:
   container_name: APP_NAME_web

volumes:
 dbdata: