# docker-compose.prod.yml

version: '3.2'

services:
  web:
    labels:
      com.example.service: "web"
      com.example.description: "Use for the main web process"
    build:
      context: ./APP_NAME/docker_compose/django/
      dockerfile: Dockerfile
    image: APP_NAME_web
    depends_on:
      - db
    command: ["./docker_compose/django/wait_for_postgres.sh"]
    environment:
      PRODUCTION: 'true'
    logging:
      driver: "json-file"
    volumes:
      - ./APP_NAME:/app

  nginx:
    restart: always
    container_name: nginx_server
    build:
      context: ./APP_NAME/docker_compose/nginx/
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "0.0.0.0:80:80"